Implemented signal handling for gracefully shutdown the server
input-output-hk/vit-servicing-station pull request #86
Opened 2020-09-02 15:12 UTC by danielSanchezQ

Implements #85

2020-09-02 15:13 UTC, danielSanchezQ commented
@dkijania 
It would be nice to have some simple tests for this at some point.

2020-09-03 13:34 UTC, mzabaluev requested changes

2020-09-03 13:34 UTC, mzabaluev commented on vit-servicing-station-lib/src/server/signals.rs
> +    let mut interrupt_stream = signal::unix::signal(signal::unix::SignalKind::interrupt())
Should be named `interrupt_signal`, I guess?

2020-09-03 13:34 UTC, mzabaluev commented on vit-servicing-station-lib/src/server/signals.rs
> +#[cfg(not(target_os = "windows"))]
I think this should be the other way around: this function's body is dependent on target_os = "unix", whereas the Windows variant is actually cross-platform, so it should be a fallback for non-UNIX.

2020-09-03 14:32 UTC, mzabaluev approved these changes

2020-09-03 15:02 UTC, merged